server:
  port: 8762

spring:
  application:
    name: eureka-server

eureka:
  instance:
    appname: ${spring.application.name}
    # eureka集群时, 在节点服务器IP一致的情况下不要使用IP注册(prefer-ip-address: true), 尽量采用修改hosts配置域名的方式, 否则集群无效
    hostname: eureka-node2
    # Eureka界面显示的应用信息
    instance-id: ${eureka.instance.hostname}:${server.port}
  server:
    # 启用自我保护机制
    enable-self-preservation: false
    # 每分钟最少续约数中的百分比例值
    # renewal-percent-threshold: 0.85
    # 每分钟最少续约数更新周期
    renewal-threshold-update-interval-ms: 60000
    # 检测注册信息续约有效性周期(毫秒)
    # eviction-interval-timer-in-ms: 60000
  client:
    # 是否将自己注册到注册中心
    # register-with-eureka: true
    # 是否需要从注册中心获取注册信息
    # fetch-registry: true
    # 从注册中心获取注册信息周期
    # registry-fetch-interval-seconds: 30
    service-url:
      # 注册中心的地址
      defaultZone: http://eureka-node1:8761/eureka/
